package dev.mateuy.safanoria.core

import okio.Path

/**
 * What a board groups tickets by: the statuses, with `done` in two, by whether a release is
 * pending ([Release.pending]). A view over `status` and `resolvedIn`, not more statuses. In
 * [TicketGraph.STATUS_ORDER].
 */
public enum class BoardGroup(public val status: Status, public val heading: String) {
    IN_PROGRESS(Status.IN_PROGRESS, "In progress"),
    REVIEW(Status.REVIEW, "Review"),
    READY(Status.READY, "Ready"),
    BACKLOG(Status.BACKLOG, "Backlog"),

    /** `done`, with a component of its area not released yet: what the next release brings. */
    TO_RELEASE(Status.DONE, "To release"),

    /** `done` with nothing pending: released in every component, or never getting a version. */
    RELEASED(Status.DONE, "Released"),
    WONTFIX(Status.WONTFIX, "Won't fix");

    public companion object {
        /** The group of [ticket], or null when its status can't be read. */
        public fun of(ticket: Ticket, config: Config): BoardGroup? = when (val status = ticket.frontmatter?.status) {
            null -> null
            Status.DONE -> if (Release.pending(ticket, config).isEmpty()) RELEASED else TO_RELEASE
            else -> entries.first { it.status == status }
        }
    }
}

/**
 * The markdown board: a section per [BoardGroup], parents with their children as a checklist. The
 * output depends only on the tickets and the project's components (no dates, stable order), so a
 * committed board changes only when they do.
 */
public object Board {
    /** The versions [ticket] was released in, e.g. `app 4.3.0, web 2.0.0`; null when it has none. */
    public fun versions(ticket: Ticket): String? = ticket.frontmatter?.resolvedIn.orEmpty()
        .mapNotNull { (component, version) -> version.value?.let { "$component $it" } }
        .takeIf { it.isNotEmpty() }?.joinToString(", ")

    /** The board, with links to ticket files relative to [linkFrom], the directory the board is written to. */
    public fun markdown(graph: TicketGraph, config: Config, linkFrom: Path): String {
        fun link(t: Ticket): String {
            val path = runCatching { t.path.relativeTo(linkFrom) }.getOrNull() ?: t.path
            return "[${t.fileId}](${path.segments.joinToString("/")})"
        }
        fun ref(id: String) = graph.ticket(id)?.let(::link) ?: "`$id`"
        /** The title, and the branch when the ticket exists only there (SPEC §14.1 rule 3). */
        fun title(t: Ticket) = (t.frontmatter?.title?.value ?: "(no title)") + (t.branch?.takeIf { t.onlyOnBranch }?.let { " · only on `$it`" } ?: "")

        /** Type and priority when not the usual ones, then progress and open blockers. */
        fun details(t: Ticket, withStatus: Boolean): String {
            val f = t.frontmatter
            val facets = listOfNotNull(
                f?.status?.text?.takeIf { withStatus },
                f?.type?.takeIf { it != TicketType.FEATURE }?.text,
                f?.priority?.takeIf { it == Priority.HIGH || it == Priority.URGENT }?.text,
            )
            val parts = listOfNotNull(
                graph.progress(t)?.takeIf { graph.children(t).isNotEmpty() }?.let { "${it.done}/${it.total}" },
                graph.openBlockers(t).takeIf { it.isNotEmpty() }?.let { ids -> "blocked by " + ids.joinToString(", ") { ref(it) } },
            )
            return (if (facets.isEmpty()) "" else facets.joinToString(", ", " (", ")")) +
                parts.joinToString("") { " · $it" }
        }

        val out = StringBuilder("# Board\n\nGenerated by `safanoria-cli board` from the tickets.\n")
        // Children are shown under their parent; a child whose parent is missing is shown on its own.
        val topLevel = graph.tickets.filter { graph.parent(it) == null }
        val groups = topLevel.groupBy { BoardGroup.of(it, config) }
        for (group in BoardGroup.entries + listOf(null)) {
            val tickets = groups[group] ?: continue
            out.append("\n## ${group?.heading ?: "Unreadable status"} (${tickets.size})\n\n")
            val closed = group?.status == Status.DONE || group?.status == Status.WONTFIX
            for (t in tickets) {
                if (closed) {
                    out.append("- ${link(t)} ${title(t)}${versions(t)?.let { " · $it" } ?: ""}\n")
                    continue
                }
                out.append("- ${link(t)} ${title(t)}${details(t, withStatus = false)}\n")
                for (child in graph.children(t)) {
                    val childStatus = child.frontmatter?.status
                    val check = if (childStatus == Status.DONE || childStatus == Status.WONTFIX) "x" else " "
                    out.append("  - [$check] ${link(child)} ${title(child)}${details(child, withStatus = childStatus != Status.DONE)}\n")
                }
            }
        }
        return out.toString()
    }
}
