package dev.mateuy.safanoria.core

import okio.Path

/**
 * The markdown board: a section per status, parents with their children as a checklist. The
 * output depends only on the tickets (no dates, stable order), so a committed board changes only
 * when they do.
 */
public object Board {
    private val HEADINGS = mapOf(
        Status.IN_PROGRESS to "In progress",
        Status.REVIEW to "Review",
        Status.READY to "Ready",
        Status.BACKLOG to "Backlog",
        Status.DONE to "Done",
        Status.WONTFIX to "Won't fix",
    )

    /** The board, with links to ticket files relative to [linkFrom], the directory the board is written to. */
    public fun markdown(graph: TicketGraph, linkFrom: Path): String {
        fun link(t: Ticket): String {
            val path = runCatching { t.path.relativeTo(linkFrom) }.getOrNull() ?: t.path
            return "[${t.fileId}](${path.segments.joinToString("/")})"
        }
        fun ref(id: String) = graph.ticket(id)?.let(::link) ?: "`$id`"
        fun title(t: Ticket) = t.frontmatter?.title?.value ?: "(no title)"

        /** Type and priority when not the usual ones, then progress and open blockers. */
        fun details(t: Ticket, withStatus: Boolean): String {
            val f = t.frontmatter
            val facets = listOfNotNull(
                f?.status?.text?.takeIf { withStatus },
                f?.type?.takeIf { it != TicketType.FEATURE }?.text,
                f?.priority?.takeIf { it == Priority.HIGH || it == Priority.URGENT }?.text,
            )
            val parts = listOfNotNull(
                graph.progress(t)?.takeIf { graph.children(t).isNotEmpty() }?.let { "${it.done}/${it.total}" },
                graph.openBlockers(t).takeIf { it.isNotEmpty() }?.let { ids -> "blocked by " + ids.joinToString(", ") { ref(it) } },
            )
            return (if (facets.isEmpty()) "" else facets.joinToString(", ", " (", ")")) +
                parts.joinToString("") { " · $it" }
        }

        val out = StringBuilder("# Board\n\nGenerated by `safanoria board` from the tickets.\n")
        // Children are shown under their parent; a child whose parent is missing is shown on its own.
        val topLevel = graph.tickets.filter { graph.parent(it) == null }
        val groups = topLevel.groupBy { it.frontmatter?.status }
        for (status in TicketGraph.STATUS_ORDER + listOf(null)) {
            val tickets = groups[status] ?: continue
            out.append("\n## ${status?.let { HEADINGS.getValue(it) } ?: "Unreadable status"} (${tickets.size})\n\n")
            val closed = status == Status.DONE || status == Status.WONTFIX
            for (t in tickets) {
                if (closed) {
                    out.append("- ${link(t)} ${title(t)}\n")
                    continue
                }
                out.append("- ${link(t)} ${title(t)}${details(t, withStatus = false)}\n")
                for (child in graph.children(t)) {
                    val childStatus = child.frontmatter?.status
                    val check = if (childStatus == Status.DONE || childStatus == Status.WONTFIX) "x" else " "
                    out.append("  - [$check] ${link(child)} ${title(child)}${details(child, withStatus = childStatus != Status.DONE)}\n")
                }
            }
        }
        return out.toString()
    }
}
