[versions]
kotlin = "2.4.20"
kaml = "0.104.0"
okio = "3.18.2"
clikt = "5.1.0"
jsonSchemaValidator = "0.5.5"
kotlinxSerialization = "1.11.0"

[libraries]
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
json-schema-validator = { module = "io.github.optimumcode:json-schema-validator", version.ref = "jsonSchemaValidator" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
