plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

// Embeds schema/*.json and the version into core, so the CLI checks exactly the schemas this
// repository publishes.
val generateEmbedded = tasks.register("generateEmbedded") {
    val schemaDir = rootProject.layout.projectDirectory.dir("schema")
    val ticketSchema = schemaDir.file("ticket.schema.json")
    val configSchema = schemaDir.file("safanoria.schema.json")
    val version = project.version.toString()
    val outDir = layout.buildDirectory.dir("generated/embedded")
    inputs.files(ticketSchema, configSchema)
    inputs.property("version", version)
    outputs.dir(outDir)
    doLast {
        // Multi-dollar raw strings: a single $ (as in "$schema") stays literal.
        fun raw(file: RegularFile) = "\$\$\"\"\"" + file.asFile.readText() + "\"\"\""
        val out = outDir.get().file("dev/mateuy/safanoria/core/Embedded.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(
            """
            |// Generated by core/build.gradle.kts from schema/ and gradle.properties. Do not edit.
            |package dev.mateuy.safanoria.core
            |
            |public object Embedded {
            |    public const val VERSION: String = "$version"
            |    public const val TICKET_SCHEMA: String = ${raw(ticketSchema)}
            |    public const val CONFIG_SCHEMA: String = ${raw(configSchema)}
            |}
            |""".trimMargin()
        )
    }
}

kotlin {
    explicitApi()
    jvmToolchain(21)
    jvm()
    linuxX64()
    mingwX64()
    macosArm64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateEmbedded)
            dependencies {
                api(libs.okio)
                implementation(libs.kaml)
                implementation(libs.json.schema.validator)
                implementation(libs.kotlinx.serialization.json)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}
