plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

// Embeds schema/*.json, templates/, the skill, SPEC.md and the version into core, so the CLI
// uses and installs exactly the files this repository publishes.
val generateEmbedded = tasks.register("generateEmbedded") {
    val schemaDir = rootProject.layout.projectDirectory.dir("schema")
    val ticketSchema = schemaDir.file("ticket.schema.json")
    val configSchema = schemaDir.file("safanoria.schema.json")
    val ticketTemplate = rootProject.layout.projectDirectory.file("templates/ticket.md")
    val skill = rootProject.layout.projectDirectory.file("skill/SKILL.md")
    val spec = rootProject.layout.projectDirectory.file("SPEC.md")
    // templates/<type>.md: built-in templates for one type (SPEC §6.2).
    val typeTemplates = listOf("feature", "bug", "maintenance", "research")
        .map { rootProject.layout.projectDirectory.file("templates/$it.md") }
        .filter { it.asFile.exists() }
    // gradle.properties holds the version being developed (plain MAJOR.MINOR.PATCH, read by
    // `safanoria-cli release` as this repository's component version). Only release builds
    // (-Prelease, from the vX.Y.Z tag) report it as is; every other build is "-dev".
    val plain = project.version.toString()
    require(Regex("""\d+\.\d+\.\d+""").matches(plain)) { "gradle.properties version must be MAJOR.MINOR.PATCH, got '$plain'" }
    val version = if (providers.gradleProperty("release").isPresent) plain else "$plain-dev"
    val outDir = layout.buildDirectory.dir("generated/embedded")
    inputs.files(ticketSchema, configSchema, ticketTemplate, typeTemplates, skill, spec)
    inputs.property("version", version)
    outputs.dir(outDir)
    doLast {
        // Multi-dollar raw strings: a single $ (as in "$schema") stays literal. They can't hold
        // """ or $$, so those fail the build rather than produce a wrong copy. No trimMargin:
        // it would strip the leading | of markdown table rows.
        fun raw(file: RegularFile): String {
            val text = file.asFile.readText()
            require("\"\"\"" !in text && "\$\$" !in text) { "${file.asFile} contains \"\"\" or \$\$, which can't be embedded" }
            return "\$\$\"\"\"" + text + "\"\"\""
        }
        val out = outDir.get().file("dev/mateuy/safanoria/core/Embedded.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(listOf(
            "// Generated by core/build.gradle.kts from schema/, templates/, skill/, SPEC.md and gradle.properties. Do not edit.",
            "package dev.mateuy.safanoria.core",
            "",
            "public object Embedded {",
            "    public const val VERSION: String = \"$version\"",
            "    public const val TICKET_SCHEMA: String = ${raw(ticketSchema)}",
            "    public const val CONFIG_SCHEMA: String = ${raw(configSchema)}",
            "    public const val TICKET_TEMPLATE: String = ${raw(ticketTemplate)}",
            "    /** Built-in template per type (`bug`, `research`); others use [TICKET_TEMPLATE]. */",
            "    public val TYPE_TEMPLATES: Map<String, String> = mapOf(",
            typeTemplates.joinToString(",\n") { "        \"${it.asFile.nameWithoutExtension}\" to ${raw(it)}" },
            "    )",
            "    /** skill/SKILL.md, installed into projects. */",
            "    public const val SKILL: String = ${raw(skill)}",
            "    /** SPEC.md, installed next to the skill. */",
            "    public const val SPEC: String = ${raw(spec)}",
            "}",
            "",
        ).joinToString("\n"))
    }
}

kotlin {
    explicitApi()
    jvmToolchain(21)
    jvm()
    linuxX64()
    mingwX64()
    macosArm64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateEmbedded)
            dependencies {
                api(libs.okio)
                implementation(libs.kaml)
                implementation(libs.json.schema.validator)
                implementation(libs.kotlinx.serialization.json)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.okio.fakefilesystem)
        }
    }
}
