plugins {
    alias(libs.plugins.kotlin.multiplatform)
}

// Embeds schema/*.json, templates/ticket.md and the version into core, so the CLI uses exactly
// the files this repository publishes.
val generateEmbedded = tasks.register("generateEmbedded") {
    val schemaDir = rootProject.layout.projectDirectory.dir("schema")
    val ticketSchema = schemaDir.file("ticket.schema.json")
    val configSchema = schemaDir.file("safanoria.schema.json")
    val ticketTemplate = rootProject.layout.projectDirectory.file("templates/ticket.md")
    // gradle.properties holds the version being developed (plain MAJOR.MINOR.PATCH, read by
    // `safanoria release` as this repository's component version). Only release builds
    // (-Prelease, from the vX.Y.Z tag) report it as is; every other build is "-dev".
    val plain = project.version.toString()
    require(Regex("""\d+\.\d+\.\d+""").matches(plain)) { "gradle.properties version must be MAJOR.MINOR.PATCH, got '$plain'" }
    val version = if (providers.gradleProperty("release").isPresent) plain else "$plain-dev"
    val outDir = layout.buildDirectory.dir("generated/embedded")
    inputs.files(ticketSchema, configSchema, ticketTemplate)
    inputs.property("version", version)
    outputs.dir(outDir)
    doLast {
        // Multi-dollar raw strings: a single $ (as in "$schema") stays literal.
        fun raw(file: RegularFile) = "\$\$\"\"\"" + file.asFile.readText() + "\"\"\""
        val out = outDir.get().file("dev/mateuy/safanoria/core/Embedded.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(
            """
            |// Generated by core/build.gradle.kts from schema/, templates/ and gradle.properties. Do not edit.
            |package dev.mateuy.safanoria.core
            |
            |public object Embedded {
            |    public const val VERSION: String = "$version"
            |    public const val TICKET_SCHEMA: String = ${raw(ticketSchema)}
            |    public const val CONFIG_SCHEMA: String = ${raw(configSchema)}
            |    public const val TICKET_TEMPLATE: String = ${raw(ticketTemplate)}
            |}
            |""".trimMargin()
        )
    }
}

kotlin {
    explicitApi()
    jvmToolchain(21)
    jvm()
    linuxX64()
    mingwX64()
    macosArm64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateEmbedded)
            dependencies {
                api(libs.okio)
                implementation(libs.kaml)
                implementation(libs.json.schema.validator)
                implementation(libs.kotlinx.serialization.json)
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.okio.fakefilesystem)
        }
    }
}
