package dev.mateuy.safanoria.core

import okio.Path.Companion.toPath
import kotlin.test.Test
import kotlin.test.assertEquals

class BoardTest {
    private fun ticket(id: String, status: String, type: String = "feature", priority: String = "medium", extra: String = "", plan: String = "") = Ticket(
        "/r/tickets/$id.md".toPath(),
        "---\nid: $id\ntype: $type\ntitle: Title $id\nstatus: $status\npriority: $priority\nsize: S\n" +
            "created: 2026-10-01\nupdated: 2026-10-01\n$extra---\n\n## Plan\n\n$plan",
    )

    @Test
    fun edgeCases() {
        val graph = TicketGraph(listOf(
            ticket("parent-one", "done", plan = "- [x] `parent-one-a`: a.\n"),
            ticket("parent-one-a", "wontfix", extra = "parent: parent-one\n"),
            ticket("orphan", "ready", "bug", "urgent", extra = "parent: missing\nblockedBy: [gone, parent-one]\n"),
            ticket("odd", "nonsense"),
        ))
        // Closed parents are compact; a child of a missing parent is shown on its own; a missing
        // blocker counts as open and isn't linked; an unknown status gets its own section.
        val expected = """
            # Board

            Generated by `safanoria-cli board` from the tickets.

            ## Ready (1)

            - [orphan](tickets/orphan.md) Title orphan (bug, urgent) · blocked by `gone`

            ## Done (1)

            - [parent-one](tickets/parent-one.md) Title parent-one

            ## Unreadable status (1)

            - [odd](tickets/odd.md) Title odd

        """.trimIndent()
        assertEquals(expected, Board.markdown(graph, "/r".toPath()))
    }
}
