package dev.mateuy.safanoria.core

import okio.Path.Companion.toPath
import kotlin.test.Test
import kotlin.test.assertEquals

class BoardTest {
    private fun ticket(id: String, status: String, type: String = "feature", priority: String = "medium", extra: String = "", plan: String = "") = Ticket(
        "/r/tickets/$id.md".toPath(),
        "---\nid: $id\ntype: $type\ntitle: Title $id\nstatus: $status\npriority: $priority\nsize: S\n" +
            "created: 2026-10-01\nupdated: 2026-10-01\n$extra---\n\n## Plan\n\n$plan",
    )

    private fun config(vararg components: String) = Config(
        "/r/safanoria.yaml".toPath(), specVersion = 1,
        components = components.associateWith { Component(it, version = null, external = false, line = 1) },
    )

    private fun group(config: Config, status: String = "done", type: String = "feature", extra: String = "") =
        BoardGroup.of(ticket("one", status, type, extra = extra), config)

    @Test
    fun doneIsToReleaseUntilEveryComponentOfItsAreaHasAVersion() {
        val two = config("app", "web")
        assertEquals(BoardGroup.TO_RELEASE, group(two, extra = "area: [app]\n"))
        assertEquals(BoardGroup.TO_RELEASE, group(two, extra = "area: [app]\nresolvedIn:\n  app: null\n"))
        assertEquals(BoardGroup.RELEASED, group(two, extra = "area: [app]\nresolvedIn:\n  app: 4.3.0\n"))
        assertEquals(BoardGroup.TO_RELEASE, group(two, extra = "area: [app, web]\nresolvedIn:\n  app: 4.3.0\n"))
        assertEquals(BoardGroup.RELEASED, group(two, extra = "area: [app, web]\nresolvedIn:\n  app: 4.3.0\n  web: 2.0.0\n"))
    }

    @Test
    fun doneWithNothingToStampIsReleased() {
        val two = config("app", "web")
        assertEquals(BoardGroup.RELEASED, group(two, type = "research", extra = "area: [app]\n"))
        assertEquals(BoardGroup.RELEASED, group(two), "no area")
        assertEquals(BoardGroup.RELEASED, group(config()), "no components")
        assertEquals(BoardGroup.RELEASED, group(two, extra = "area: [gone]\n"), "not a component: never stamped")
    }

    @Test
    fun withOneComponentATicketWithNoAreaIsOfIt() {
        // As stamping reads it: `release` stamps these, so until then they are to release.
        val one = config("app")
        assertEquals(BoardGroup.TO_RELEASE, group(one))
        assertEquals(BoardGroup.RELEASED, group(one, extra = "resolvedIn:\n  app: 4.3.0\n"))
        assertEquals(BoardGroup.RELEASED, group(one, type = "research"))
    }

    @Test
    fun otherStatusesAreTheirOwnGroup() {
        val one = config("app")
        assertEquals(BoardGroup.IN_PROGRESS, group(one, status = "in-progress"))
        assertEquals(BoardGroup.WONTFIX, group(one, status = "wontfix"))
        assertEquals(null, group(one, status = "nonsense"))
    }

    @Test
    fun doneIsTwoSections() {
        val graph = TicketGraph(listOf(
            ticket("waiting", "done"),
            ticket("shipped", "done", extra = "resolvedIn:\n  app: 4.3.0\n"),
            ticket("study", "done", "research"),
        ))
        val expected = """
            # Board

            Generated by `safanoria-cli board` from the tickets.

            ## To release (1)

            - [waiting](tickets/waiting.md) Title waiting

            ## Released (2)

            - [shipped](tickets/shipped.md) Title shipped · app 4.3.0
            - [study](tickets/study.md) Title study

        """.trimIndent()
        assertEquals(expected, Board.markdown(graph, config("app"), "/r".toPath()))
    }

    @Test
    fun edgeCases() {
        val graph = TicketGraph(listOf(
            ticket("parent-one", "done", plan = "- [x] `parent-one-a`: a.\n"),
            ticket("parent-one-a", "wontfix", extra = "parent: parent-one\n"),
            ticket("orphan", "ready", "bug", "urgent", extra = "parent: missing\nblockedBy: [gone, parent-one]\n"),
            ticket("odd", "nonsense"),
        ))
        // Closed parents are compact; a child of a missing parent is shown on its own; a missing
        // blocker counts as open and isn't linked; an unknown status gets its own section.
        val expected = """
            # Board

            Generated by `safanoria-cli board` from the tickets.

            ## Ready (1)

            - [orphan](tickets/orphan.md) Title orphan (bug, urgent) · blocked by `gone`

            ## Released (1)

            - [parent-one](tickets/parent-one.md) Title parent-one

            ## Unreadable status (1)

            - [odd](tickets/odd.md) Title odd

        """.trimIndent()
        assertEquals(expected, Board.markdown(graph, config(), "/r".toPath()))
    }
}
